name: 'Restore and Test Database'
description: 'Check if database backup is valid'
inputs:
  config-path:  # id of input
    description: 'config path'
    required: true
    default: './config.yaml'
runs:
  using: "composite"
  steps:
    - run: |
        wget https://github.com/takutakahashi/database-restore-action/releases/download/v0.9.0/database-restore-action_0.9.0_linux_amd64.tar.gz
        tar vzxf database-restore-action_0.9.0_linux_amd64.tar.gz
      shell: bash
    - run: ./database-restore-action -c ${{ inputs.config-path }}
      shell: bash
